Add changeset_url to challenge schema
maproulette/maproulette2 pull request #894
Opened 2021-05-14 04:12 UTC by jschwarz2030

resolves https://github.com/osmlab/maproulette3/issues/178

2021-05-14 17:32 UTC, mgcuthbert requested changes
Could you explain more how this resolves osmlab/maproulette3#178, I doesn't seem to. Also what exactly is changeset_url referencing? Based on the above issue it would imply that the url is the challenge url and not some changeset. If it was a changeset though which changeset would it exactly be?

2021-05-14 17:44 UTC, jschwarz2030 commented
I may not be titling the column name very well.  Basically we are adding a boolean to the challenge that will later determine if a url back to the challenge should be constructed and added to the changeset comment when a task is worked on.  The url is built in the FE and will attach it to the comment if changesetUrl is true.

2021-05-17 16:36 UTC, mgcuthbert commented
Ok thanks, that makes sense.

2021-05-17 16:36 UTC, mgcuthbert approved these changes

2021-05-17 16:36 UTC, merged